### PR TITLE
Update LFortran to 0.6.0

### PR DESCRIPTION
**Pull request by certik**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

Closes: #5
Closes: #6
Closes: #7
Closes: #8
Closes: #9

### CODE REVIEW

**Comment by certik** [comment]
@conda-forge-admin, please rerender

**Comment by certik** [comment]
Weird, the error [is](https://dev.azure.com/conda-forge/84710dde-1620-425b-80d0-4cf5baca359d/_apis/build/builds/201033/logs/13):
```
2020-08-25T19:07:36.0054411Z /home/conda/feedstock_root/build_artifacts/lfortran_1598382241704/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pl/include/llvm/Object/SymbolicFile.h:47:31: error: expected ')' before 'PRIxPTR'
2020-08-25T19:07:36.0055316Z    OS << "(" << format("0x%08" PRIxPTR, D.p) << " (" << format("0x%08x", D.d.a)
2020-08-25T19:07:36.0055790Z                                ^~~~~~~
```
But the exact same LLVM and gcc compiler versions work on my computer.

**Comment by certik** [comment]
The `PRIxPTR` failure was fixed by 5905f40418c14b198d3cbdf9dbea09822653f05c.

Now the failure is (and 04ed1be842a33063604b5125388c8eb74063b47a didn't fix it):
```
[ 48%] Linking CXX executable test_pickle
/home/conda/feedstock_root/build_artifacts/lfortran_1598384343690/_build_env/bin/../lib/gcc/x86_64-conda-linux-gnu/7.5.0/../../../../x86_64-conda-linux-gnu/bin/ld: /tmp/ccuzMzX1.ltrans0.ltrans.o: in function `_DOCTEST_ANON_FUNC_12()':
<artificial>:(.text._ZL21_DOCTEST_ANON_FUNC_12v+0x52): undefined reference to `LFortran::parse(Allocator&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
/home/conda/feedstock_root/build_artifacts/lfortran_1598384343690/_build_env/bin/../lib/gcc/x86_64-conda-linux-gnu/7.5.0/../../../../x86_64-conda-linux-gnu/bin/ld: <artificial>:(.text._ZL21_DOCTEST_ANON_FUNC_12v+0x154): undefined reference to `LFortran::pickle[abi:cxx11](LFortran::AST::ast_t&, bool)'
/home/conda/feedstock_root/build_artifacts/lfortran_1598384343690/_build_env/bin/../lib/gcc/x86_64-conda-linux-gnu/7.5.0/../../../../x86_64-conda-linux-gnu/bin/ld: <artificial>:(.text._ZL21_DOCTEST_ANON_FUNC_12v+0x221): undefined reference to `LFortran::pickle[abi:cxx11](LFortran::AST::ast_t&, bool)'
/home/conda/feedstock_root/build_artifacts/lfortran_1598384343690/_build_env/bin/../lib/gcc/x86_64-conda-linux-gnu/7.5.0/../../../../x86_64-conda-linux-gnu/bin/ld: <artificial>:(.text._ZL21_DOCTEST_ANON_FUNC_12v+0x2c1): undefined reference to `LFortran::parse(Allocator&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
/home/conda/feedstock_root/build_artifacts/lfortran_1598384343690/_build_env/bin/../lib/gcc/x86_64-conda-linux-gnu/7.5.0/../../../../x86_64-conda-linux-gnu/bin/ld: <artificial>:(.text._ZL21_DOCTEST_ANON_FUNC_12v+0x3b8): undefined reference to `LFortran::pickle[abi:cxx11](LFortran::AST::ast_t&, bool)'
/home/conda/feedstock_root/build_artifacts/lfortran_1598384343690/_build_env/bin/../lib/gcc/x86_64-conda-linux-gnu/7.5.0/../../../../x86_64-conda-linux-gnu/bin/ld: <artificial>:(.text._ZL21_DOCTEST_ANON_FUNC_12v+0x485): undefined reference to `LFortran::pickle[abi:cxx11](LFortran::AST::ast_t&, bool)'
/home/conda/feedstock_root/build_artifacts/lfortran_1598384343690/_build_env/bin/../lib/gcc/x86_64-conda-linux-gnu/7.5.0/../../../../x86_64-conda-linux-gnu/bin/ld: <artificial>:(.text._ZL21_DOCTEST_ANON_FUNC_12v+0x523): undefined reference to `LFortran::parse(Allocator&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
/home/conda/feedstock_root/build_artifacts/lfortran_1598384343690/_build_env/bin/../lib/gcc/x86_64-conda-linux-gnu/7.5.0/../../../../x86_64-conda-linux-gnu/bin/ld: <artificial>:(.text._ZL21_DOCTEST_ANON_FUNC_12v+0x61a): undefined reference to `LFortran::pickle[abi:cxx11](LFortran::AST::ast_t&, bool)'
/home/conda/feedstock_root/build_artifacts/lfortran_1598384343690/_build_env/bin/../lib/gcc/x86_64-conda-linux-gnu/7.5.0/../../../../x86_64-conda-linux-gnu/bin/ld: <artificial>:(.text._ZL21_DOCTEST_ANON_FUNC_12v+0x6e9): undefined reference to `LFortran::pickle[abi:cxx11](LFortran::AST::ast_t&, bool)'
/home/conda/feedstock_root/build_artifacts/lfortran_1598384343690/_build_env/bin/../lib/gcc/x86_64-conda-linux-gnu/7.5.0/../../../../x86_64-conda-linux-gnu/bin/ld: <artificial>:(.text._ZL21_DOCTEST_ANON_FUNC_12v+0x787): undefined reference to `LFortran::parse(Allocator&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
/home/conda/feedstock_root/build_artifacts/lfortran_1598384343690/_build_env/bin/../lib/gcc/x86_64-conda-linux-gnu/7.5.0/../../../../x86_64-conda-linux-gnu/bin/ld: <artificial>:(.text._ZL21_DOCTEST_ANON_FUNC_12v+0x87c): undefined reference to `LFortran::pickle[abi:cxx11](LFortran::AST::ast_t&, bool)'
/home/conda/feedstock_root/build_artifacts/lfortran_1598384343690/_build_env/bin/../lib/gcc/x86_64-conda-linux-gnu/7.5.0/../../../../x86_64-conda-linux-gnu/bin/ld: <artificial>:(.text._ZL21_DOCTEST_ANON_FUNC_12v+0x94b): undefined reference to `LFortran::pickle[abi:cxx11](LFortran::AST::ast_t&, bool)'
/home/conda/feedstock_root/build_artifacts/lfortran_1598384343690/_build_env/bin/../lib/gcc/x86_64-conda-linux-gnu/7.5.0/../../../../x86_64-conda-linux-gnu/bin/ld: <artificial>:(.text._ZL21_DOCTEST_ANON_FUNC_12v+0xa1a): undefined reference to `LFortran::pickle[abi:cxx11](LFortran::AST::ast_t&, bool)'
/home/conda/feedstock_root/build_artifacts/lfortran_1598384343690/_build_env/bin/../lib/gcc/x86_64-conda-linux-gnu/7.5.0/../../../../x86_64-conda-linux-gnu/bin/ld: <artificial>:(.text._ZL21_DOCTEST_ANON_FUNC_12v+0xab8): undefined reference to `LFortran::parse(Allocator&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
/home/conda/feedstock_root/build_artifacts/lfortran_1598384343690/_build_env/bin/../lib/gcc/x86_64-conda-linux-gnu/7.5.0/../../../../x86_64-conda-linux-gnu/bin/ld: <artificial>:(.text._ZL21_DOCTEST_ANON_FUNC_12v+0xbad): undefined reference to `LFortran::pickle[abi:cxx11](LFortran::AST::ast_t&, bool)'
/home/conda/feedstock_root/build_artifacts/lfortran_1598384343690/_build_env/bin/../lib/gcc/x86_64-conda-linux-gnu/7.5.0/../../../../x86_64-conda-linux-gnu/bin/ld: <artificial>:(.text._ZL21_DOCTEST_ANON_FUNC_12v+0xc7c): undefined reference to `LFortran::pickle[abi:cxx11](LFortran::AST::ast_t&, bool)'
/home/conda/feedstock_root/build_artifacts/lfortran_1598384343690/_build_env/bin/../lib/gcc/x86_64-conda-linux-gnu/7.5.0/../../../../x86_64-conda-linux-gnu/bin/ld: <artificial>:(.text._ZL21_DOCTEST_ANON_FUNC_12v+0xd4b): undefined reference to `LFortran::pickle[abi:cxx11](LFortran::AST::ast_t&, bool)'
/home/conda/feedstock_root/build_artifacts/lfortran_1598384343690/_build_env/bin/../lib/gcc/x86_64-conda-linux-gnu/7.5.0/../../../../x86_64-conda-linux-gnu/bin/ld: <artificial>:(.text._ZL21_DOCTEST_ANON_FUNC_12v+0xe18): undefined reference to `LFortran::pickle[abi:cxx11](LFortran::AST::ast_t&, bool)'
/home/conda/feedstock_root/build_artifacts/lfortran_1598384343690/_build_env/bin/../lib/gcc/x86_64-conda-linux-gnu/7.5.0/../../../../x86_64-conda-linux-gnu/bin/ld: /tmp/ccuzMzX1.ltrans0.ltrans.o: in function `p(Allocator&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)':
<artificial>:(.text._Z1pR9AllocatorRKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE+0x2c): undefined reference to `LFortran::parse2(Allocator&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
/home/conda/feedstock_root/build_artifacts/lfortran_1598384343690/_build_env/bin/../lib/gcc/x86_64-conda-linux-gnu/7.5.0/../../../../x86_64-conda-linux-gnu/bin/ld: <artificial>:(.text._Z1pR9AllocatorRKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE+0x4e): undefined reference to `LFortran::pickle[abi:cxx11](LFortran::AST::ast_t&, bool)'
/home/conda/feedstock_root/build_artifacts/lfortran_1598384343690/_build_env/bin/../lib/gcc/x86_64-conda-linux-gnu/7.5.0/../../../../x86_64-conda-linux-gnu/bin/ld: <artificial>:(.text._Z1pR9AllocatorRKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE+0x5a): undefined reference to `LFortran::ast_to_src[abi:cxx11](LFortran::AST::ast_t&)'
collect2: error: ld returned 1 exit status
```

**Comment by certik** [comment]
Still the same errors. It seems unrelated to the C++ standard.

**Comment by certik** [comment]
I was able to reproduce this locally as follows:
```
$ docker run -it condaforge/linux-anvil-comp7
# git clone https://github.com/certik/lfortran-feedstock
# cd lfortran-feedstock
# git checkout -t origin/update
# conda build .
[...]
/opt/conda/conda-bld/lfortran_1598392184214/_build_env/bin/../lib/gcc/x86_64-conda-linux-gnu/9.3.0/../../../../x86_64-conda-linux-gnu/bin/ld: /tmp/test_pickle.4VWAod.ltrans0.ltrans.o: in function `p(Allocator&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)':
<artificial>:(.text+0x427): undefined reference to `LFortran::parse2(Allocator&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
/opt/conda/conda-bld/lfortran_1598392184214/_build_env/bin/../lib/gcc/x86_64-conda-linux-gnu/9.3.0/../../../../x86_64-conda-linux-gnu/bin/ld: <artificial>:(.text+0x46c): undefined reference to `LFortran::pickle[abi:cxx11](LFortran::AST::ast_t&, bool)'
/opt/conda/conda-bld/lfortran_1598392184214/_build_env/bin/../lib/gcc/x86_64-conda-linux-gnu/9.3.0/../../../../x86_64-conda-linux-gnu/bin/ld: <artificial>:(.text+0x482): undefined reference to `LFortran::ast_to_src[abi:cxx11](LFortran::AST::ast_t&)'
/opt/conda/conda-bld/lfortran_1598392184214/_build_env/bin/../lib/gcc/x86_64-conda-linux-gnu/9.3.0/../../../../x86_64-conda-linux-gnu/bin/ld: /tmp/test_pickle.4VWAod.ltrans0.ltrans.o: in function `_DOCTEST_ANON_FUNC_12()':
<artificial>:(.text+0x6e0a): undefined reference to `LFortran::parse(Allocator&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
/opt/conda/conda-bld/lfortran_1598392184214/_build_env/bin/../lib/gcc/x86_64-conda-linux-gnu/9.3.0/../../../../x86_64-conda-linux-gnu/bin/ld: <artificial>:(.text+0x6f6a): undefined reference to `LFortran::pickle[abi:cxx11](LFortran::AST::ast_t&, bool)'
...
```

**Comment by certik** [comment]
I tried the same with `condaforge/linux-anvil-cos7-x86_64` per the [documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html#using-centos-7), but the same errors happen:
```
/opt/conda/conda-bld/lfortran_1598392869774/_build_env/bin/../lib/gcc/x86_64-conda-linux-gnu/9.3.0/../../../../x86_64-conda-linux-gnu/bin/ld: /tmp/test_pickle.uBb9S2.ltrans0.ltrans.o: in function `p(Allocator&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)':
<artificial>:(.text+0x427): undefined reference to `LFortran::parse2(Allocator&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
/opt/conda/conda-bld/lfortran_1598392869774/_build_env/bin/../lib/gcc/x86_64-conda-linux-gnu/9.3.0/../../../../x86_64-conda-linux-gnu/bin/ld: <artificial>:(.text+0x46c): undefined reference to `LFortran::pickle[abi:cxx11](LFortran::AST::ast_t&, bool)'
/opt/conda/conda-bld/lfortran_1598392869774/_build_env/bin/../lib/gcc/x86_64-conda-linux-gnu/9.3.0/../../../../x86_64-conda-linux-gnu/bin/ld: <artificial>:(.text+0x482): undefined reference to `LFortran::ast_to_src[abi:cxx11](LFortran::AST::ast_t&)'
/opt/conda/conda-bld/lfortran_1598392869774/_build_env/bin/../lib/gcc/x86_64-conda-linux-gnu/9.3.0/../../../../x86_64-conda-linux-gnu/bin/ld: /tmp/test_pickle.uBb9S2.ltrans0.ltrans.o: in function `_DOCTEST_ANON_FUNC_12()':
<artificial>:(.text+0x6e0a): undefined reference to `LFortran::parse(Allocator&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
/opt/conda/conda-bld/lfortran_1598392869774/_build_env/bin/../lib/gcc/x86_64-conda-linux-gnu/9.3.0/../../../../x86_64-conda-linux-gnu/bin/ld: <artificial>:(.text+0x6f6a): undefined reference to `LFortran::pickle[abi:cxx11](LFortran::AST::ast_t&, bool)'
```

**Comment by certik** [comment]
Found the problem --- LLVM for some reason introduces `-flto` to compile all the files with, and somehow it fails at link time. The solution is to disable this flag.
